### ISSUE TITLE
KafkaExtension.registerListeners() should make use of @WithAnnotations

### ISSUE THREAD

**Issue by mkouba** [matzew/cafdi#2]
To speedup the CDI bootstrap. See also http://docs.jboss.org/cdi/spec/1.2/cdi-spec.html#process_annotated_type.

**Comment by matzew** [comment]
The `@Consumer` is only for methods, that's why I did not add it to the PAT.

Perhaps there are different ways :)

**Comment by mkouba** [comment]
Well, if you use `void registerListeners(@Observes @WithAnnotations(Consumer.class) ProcessAnnotatedType pat)` then only PAT events for types which contain at least one `@Consumer` specified will be delivered. The annotation can appear on on any member, incl. methods. Right now, PAT for every type is delivered and processed.

**Comment by matzew** [comment]
@mkouba thanks :-)

here is my PR: https://github.com/matzew/cafdi/pull/4
